apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: output
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning workspace..."
        rm -rf /workspace/output/*

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-tests
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: python:3.11
      script: |
        #!/bin/sh
        pip install nose
        nosetests
